In [1]:
import pandas as pd
import numpy as np

x_train: (50000, 21)
x_test: (44727, 21)
y_train: (50000,)
y_test: (44727,)
[[ 1489  1460]
 [  744 46307]]
[[ 1314  1300]
 [  686 41427]]


In [2]:
data = pd.read_csv('hw01_data_points.csv', header=None)
labels = pd.read_csv('hw01_class_labels.csv', header=None)

In [3]:
def train_test_split(data, labels):
    return data[:50000].values, labels[:50000].values.ravel(), data[50000:].values, labels[50000:].values.ravel()

In [4]:
x_train, y_train, x_test, y_test = train_test_split(data, labels)

In [5]:
print("x_train:",x_train.shape)
print("x_test:",x_test.shape)
print("y_train:",y_train.shape)
print("y_test:",y_test.shape)

x_train: (50000, 21)
x_test: (44727, 21)
y_train: (50000,)
y_test: (44727,)


In [14]:
def estimate_prior_probabilities(y_train):
    unique_classes = np.unique(y_train)
    PR = [np.sum(y_train == c)/(y_train.size) for c in unique_classes]
    return PR
class_priors=estimate_prior_probabilities(y_train)
print(class_priors)

[0.04466, 0.95534]


In [15]:
def estimate_nucleotide_probabilities(x_train, y_train):
    unique_classes = np.unique(y_train)
    unique_x = np.unique(x_train)
    destinations = x_train.shape[1]

    indexs = x_train.shape[0]
    #res = [[[[(x_train[i][d] == x and y_train[i]==c) for d in range(0, destinations-1)] for i in range(0,indexs-1)] for c in unique_classes] for x in unique_x]
    #res = [[[np.sum(x_train[:][d] == x) / np.sum(y_train == c) for d in range(0,destinations)] for c in unique_classes] for x in unique_x]
    P=[]
     
    P =  [
            [
                [
                    sum(
                        x_train[i, d] == x and y_train[i] == c
                        for i in range(indexs)
                    ) / np.sum(y_train == c)
                    for d in range(destinations)
                ]
                for c in unique_classes
            ]
            for x in unique_x
        ]
    return P
        
P = estimate_nucleotide_probabilities(x_train, y_train)
print(P)

[[[0.18674429019256605, 0.17913121361397225, 0.14375279892521273, 0.13390058217644424, 0.11912225705329153, 0.11374832064487236, 0.10523958799820869, 0.10076130765785939, 0.08687863860277653, 0.0761307657859382, 0.06941334527541423, 0.08687863860277653, 0.10120913569189431, 0.09628302731751008, 0.08105687416032244, 0.07926556202418271, 0.23510971786833856, 0.050156739811912224, 0.24540976265114195, 0.23734885803851322, 0.25391849529780564], [0.2683233194464798, 0.2771997404065568, 0.27232189586953337, 0.25808612640525885, 0.2815332761111227, 0.277848724014487, 0.27219628613896624, 0.2608704754328302, 0.2548830782757971, 0.2661879540268386, 0.2738501475914334, 0.26955848179705655, 0.289132664810434, 0.2848619339711516, 0.27694852094542255, 0.2526011681704943, 0.2776603094186363, 0.24981681914292295, 0.28335461720434607, 0.28025624385035697, 0.2927962819519752]], [[0.2861621137483206, 0.2852664576802508, 0.2857142857142857, 0.2942230183609494, 0.3116883116883117, 0.31751007613076576, 0.3

In [ ]:
def findIndex(arr, element):
    index=0
    for a in arr:
        if a == element:
            return index
        index += 1
    return -1

In [34]:
def calculate_score_values(x, P, class_priors, unique_classes):
    unique_x = np.unique(x)
    destinations = x.shape[1]
    indexs = x.shape[0]
    
    score_list=[]
    for i in range(indexs):
        arr=[]
        for c in range(0,2):
            score=1
            for d in range(destinations):
                score = score * P[findIndex(unique_x, x[i][d])][c][d]
            score = np.log(score) + np.log(class_priors[c])
            arr.append(score)
        score_list.append(arr)
    return score_list

In [35]:
unique_classes_train = np.unique(y_train)
score_list_train= calculate_score_values(x_train, P, class_priors, unique_classes_train)
print(score_list_train)
unique_classes_test = np.unique(y_test)
score_list_test= calculate_score_values(x_test, P, class_priors, unique_classes_test)
print(score_list_test)

[[-32.29602984431623, -28.676318050300893], [-35.365109323176334, -29.066878491234593], [-33.15947789535654, -28.508292963930334], [-35.95843361321059, -29.099905915402246], [-33.24396546276087, -28.88805634609033], [-31.058453016104416, -29.161206566145488], [-41.5915582136225, -29.24124070740908], [-34.98274931197689, -28.954861877059237], [-39.85645916758563, -29.126400192164983], [-37.027917418013715, -29.174267372788368], [-38.44383984024356, -28.478326149049792], [-36.84885522787584, -28.202974846327315], [-38.56400110935342, -28.53959379908119], [-43.30621292790505, -28.938920749549357], [-31.083344870336806, -30.20141507959623], [-37.041835792664244, -28.93238720364294], [-36.629265867363365, -29.150849386324506], [-38.898984255401494, -28.701001433235696], [-46.47531593244482, -28.50952758676275], [-45.75252268242049, -28.067206191196878], [-41.21388118710017, -28.700926283255356], [-31.551326926750015, -30.171073187778354], [-42.560094295723104, -28.278650347193057], [-33.413

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



In [54]:
def calculate_confusion_matrix(y, scores):
    predicted_classes = np.argmax(scores, axis=1)
    predicted_classes= [p + 1 for p in predicted_classes]
    
    num_classes = len(np.unique(y))
    print(num_classes)
    confusion_matrix = np.zeros((num_classes, num_classes), dtype=int)
    for true_class, predicted_class in zip(y, predicted_classes):
        confusion_matrix[predicted_class - 1, true_class - 1] += 1
    return confusion_matrix

2
[[ 1489  1460]
 [  744 46307]]


In [55]:
confusion_matrix_train = calculate_confusion_matrix(y_train, score_list_train)
confusion_matrix_test = calculate_confusion_matrix(y_test, score_list_test)

2
[[ 1489  1460]
 [  744 46307]]
2
[[ 1314  1300]
 [  686 41427]]
